Updated init.d/nginx to reasonable Ubuntu version

diff --git a/cookbooks/passenger_nginx/templates/default/nginx.init.erb b/cookbooks/passenger_nginx/templates/default/nginx.init.erb
--- a/cookbooks/passenger_nginx/templates/default/nginx.init.erb
+++ b/cookbooks/passenger_nginx/templates/default/nginx.init.erb
@@ -1,92 +1,112 @@
-#!/bin/sh
-#
-# nginx
-#
-# chkconfig:   - 57 47
-# description: nginx
-# processname:  nginx
-# config:       /etc/sysconfig/nginx
-#
+#! /bin/sh
 
-# Source function library.
+### BEGIN INIT INFO
+# Provides:		nginx
+# Required-Start:	$remote_fs $syslog
+# Required-Stop:	$remote_fs $syslog
+# Default-Start:	2 3 4 5
+# Default-Stop:		
+# Short-Description:	NginX Web Server
+### END INIT INFO
+
+set -e
+
+# /etc/init.d/nginx: start and stop NginX
+
+test -x /usr/sbin/nginx || exit 0
+( /usr/sbin/nginx -\? 2>&1 | grep -q nginx ) 2>/dev/null || exit 0
+
+umask 022
+
+if test -f /etc/sysconfig/nginx; then
+    . /etc/sysconfig/nginx
+fi
+
 . /lib/lsb/init-functions
 
-# Source networking configuration.
-#. /etc/sysconfig/network
+if [ -n "$2" ]; then
+    NGINX_OPTS="$NGINX_OPTS $2"
+fi
 
-# Check that networking is up.
-#[ "$NETWORKING" = "no" ] && exit
-exec=<%= node[:nginx][:binary] %>
-prog=$(basename $exec)
-
-# default options, overruled by items in sysconfig
-NGINX_GLOBAL=""
-
-[ -e /etc/sysconfig/nginx ] && . /etc/sysconfig/nginx
-
-lockfile=/var/lock/subsys/nginx
-
-start() {
-    [ -x $exec ] || exit 5
-    echo -n $"Starting $prog: "
-    # if not running, start it up here, usually something like "daemon $exec"
-    options=""
-    if [ "${NGINX_GLOBAL}" != ""  ]; then
-        options="-g ${NGINX_GLOBAL}"
-    fi
-    $exec $options
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && touch $lockfile
-	return $retval
+# Are we running from init?
+run_by_init() {
+    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
 }
 
-stop() {
-	echo -n $"Stopping $prog: "
-	$exec -s stop
-	retval=$?
-	echo
-	[ $retval -eq 0 ] && rm -f $lockfile
-	return $retval
-}
+export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
 
-restart() {
-    stop
-    start
-}
-
-reload() {
-	echo -n $"Reloading $prog: "
-	$exec -s reload
-	retval=$?
-	echo
-	[ $retval -eq 0 ] && rm -f $lockfile
-	return $retval
-}
-
-# See how we were called.
-case "$1" in 
+case "$1" in
   start)
-        start
-        ;;
+	log_daemon_msg "Starting NginX Web Server" "nginx"
+	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/nginx.pid --exec /usr/sbin/nginx -- $NGINX_OPTS; then
+	    log_end_msg 0
+	else
+	    log_end_msg 1
+	fi
+	;;
   stop)
-        stop
-        ;;
-  status)
-        status nginx
-        ;;
-  restart)
-        restart
-        ;;
+	log_daemon_msg "Stopping NGinX Web Server" "nginx"
+	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/nginx.pid; then
+	    log_end_msg 0
+	else
+	    log_end_msg 1
+	fi
+	;;
+
   reload|force-reload)
-		reload
+	log_daemon_msg "Reloading NGinX Web Server's configuration" "nginx"
+	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /var/run/nginx.pid --exec /usr/sbin/nginx; then
+	    log_end_msg 0
+	else
+	    log_end_msg 1
+	fi
+	;;
+
+  restart)
+	log_daemon_msg "Restarting NGinX Web Server" "nginx"
+	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/nginx.pid
+	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/nginx.pid --exec /usr/sbin/nginx -- $NGINX_OPTS; then
+	    log_end_msg 0
+	else
+	    log_end_msg 1
+	fi
+	;;
+
+  try-restart)
+	log_daemon_msg "Restarting NGinX Web Server" "nginx"
+	set +e
+	start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/nginx.pid
+	RET="$?"
+	set -e
+	case $RET in
+	    0)
+		# old daemon stopped
+		if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/nginx.pid --exec /usr/sbin/nginx -- $NGINX_OPTS; then
+		    log_end_msg 0
+		else
+		    log_end_msg 1
+		fi
 		;;
-  condrestart)
-        [ -f $lockfile ] && restart || :
-        ;;
+	    1)
+		# daemon not running
+		log_progress_msg "(not running)"
+		log_end_msg 0
+		;;
+	    *)
+		# failed to stop
+		log_progress_msg "(failed to stop)"
+		log_end_msg 1
+		;;
+	esac
+	;;
+
+  status)
+	status_of_proc -p /var/run/nginx.pid /usr/sbin/nginx nginx && exit 0 || exit $?
+	;;
+
   *)
-        echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
-        exit 1 
+	log_action_msg "Usage: /etc/init.d/nginx {start|stop|reload|force-reload|restart|try-restart|status}"
+	exit 1
 esac
 
-exit $?
+exit 0
